config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :products do
    get :list, on: :collection
  end
  resources :line_items, only: [:create]
  resources :carts, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items

  def product_ids
    self.line_items.map(&:product_id)
  end

  def total_quantity
    self.line_items.sum(&:quantity)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cart

  def set_cart
    if session[:cart_id]
      cart = Cart.find_by(id: session[:cart_id])
      cart.present? ? (@current_cart = cart) : (session[:cart_id] = nil)
    end
    return unless session[:cart_id].nil?

    @current_cart = Cart.create
    session[:cart_id] = @current_cart.id
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @line_items = @current_cart.line_items.includes(:product)
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    chosen_product = Product.find(params[:product_id])
    add_items_to_cart(chosen_product, params[:quantity].to_i)
    respond_to do |format|
      if @line_item.save!
        format.html { redirect_back(fallback_location: @current_cart) }
        format.js
      else
        format.html { render :new, notice: 'Error adding product to basket!' }
      end
    end
  end

  private
  def add_items_to_cart(chosen_product, quantity = 1)
    # If cart already has this product then find the relevant line_item
    # and iterate quantity otherwise create a new line_item for this product
    if @current_cart.product_ids.include?(chosen_product.id)
      # Find the line_item with the chosen_product
      @line_item = @current_cart.line_items.find_by(product_id: chosen_product)
      # Iterate the line_item's quantity by one
      @line_item.quantity += quantity
    else
      @line_item = LineItem.new
      @line_item.cart = @current_cart
      @line_item.product = chosen_product
      # @line_item.order = Order.first
      @line_item.quantity = quantity
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  def index
    @products = Product.all
  end

  def list
    @products = Product.all
  end

  def show; end

  def edit; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to list_products_url
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :image, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_line_item.html.erb
<tr>
  <td>
    <div class="media">
      <div class="d-flex">
        <img
          src="<%= line_item.product.image %>"
          alt=""
          class="h-100px"
          />
      </div>
      <div class="media-body">
        <p><%= line_item.product.name %></p>
      </div>
    </div>
  </td>
  <td>
    <h5>$<%= line_item.product.price %></h5>
  </td>
  <td>
    <div class="product_count">
      <input
        type="text"
        name="qty"
        id="sst"
        maxlength="12"
        value="<%= line_item.quantity %>"
        title="Quantity:"
        class="input-text qty"
        />
      <button
        onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
        class="increase items-count"
        type="button"
      >
        <i class="lnr lnr-chevron-up"></i>
      </button>
      <button
        onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
        class="reduced items-count"
        type="button"
      >
        <i class="lnr lnr-chevron-down"></i>
      </button>
    </div>
  </td>
  <td>
    <h5>$<%= line_item.product.price * line_item.quantity %></h5>
  </td>
</tr>

app/views/carts/index.html.erb
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div class="container">
      <div
        class="banner_content d-md-flex justify-content-between align-items-center"
      >
        <div class="mb-3 mb-md-0">
          <h2>Cart</h2>
          <p>Very us move be blessed multiply night</p>
        </div>
        <div class="page_link">
          <a href="index.html">Home</a>
          <a href="cart.html">Cart</a>
        </div>
      </div>
    </div>
  </div>
</section>

<!--================Cart Area =================-->
<section class="cart_area">
  <div class="container">
    <div class="cart_inner">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total</th>
          </tr>
          </thead>
          <tbody>
          <% @line_items.each do |line_item| %>
            <%= render 'line_item', line_item: line_item %>
          <% end %>
          <tr class="bottom_button">
            <td>
              <a class="gray_btn" href="#">Update Cart</a>
            </td>
            <td></td>
            <td></td>
            <td>
              <div class="cupon_text">
                <input type="text" placeholder="Coupon Code" />
                <a class="main_btn" href="#">Apply</a>
                <a class="gray_btn" href="#">Close Coupon</a>
              </div>
            </td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td>
              <h5>Subtotal</h5>
            </td>
            <td>
              <h5>$2160.00</h5>
            </td>
          </tr>
          <tr class="shipping_area">
            <td></td>
            <td></td>
            <td>
              <h5>Shipping</h5>
            </td>
            <td>
              <div class="shipping_box">
                <ul class="list">
                  <li>
                    <a href="#">Flat Rate: $5.00</a>
                  </li>
                  <li>
                    <a href="#">Free Shipping</a>
                  </li>
                  <li>
                    <a href="#">Flat Rate: $10.00</a>
                  </li>
                  <li class="active">
                    <a href="#">Local Delivery: $2.00</a>
                  </li>
                </ul>
                <h6>
                  Calculate Shipping
                  <i class="fa fa-caret-down" aria-hidden="true"></i>
                </h6>
                <select class="shipping_select">
                  <option value="1">Bangladesh</option>
                  <option value="2">India</option>
                  <option value="4">Pakistan</option>
                </select>
                <select class="shipping_select">
                  <option value="1">Select a State</option>
                  <option value="2">Select a State</option>
                  <option value="4">Select a State</option>
                </select>
                <input type="text" placeholder="Postcode/Zipcode" />
                <a class="gray_btn" href="#">Update Details</a>
              </div>
            </td>
          </tr>
          <tr class="out_button_area">
            <td></td>
            <td></td>
            <td></td>
            <td>
              <div class="checkout_btn_inner">
                <a class="gray_btn" href="#">Continue Shopping</a>
                <a class="main_btn" href="#">Proceed to checkout</a>
              </div>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
<!--================End Cart Area =================-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGirlShoppingDemo</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" href="/img/favicon.png" type="image/png" />
    <%= render partial: 'partials/include_css' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="/js/jquery-3.2.1.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'partials/header' %>
    <%= yield %>
    <%= render partial: 'partials/footer' %>
    <%= render partial: 'partials/include_script' %>
  </body>
</html>

app/views/line_items/create.html.erb
<h1>LineItems#create</h1>
<p>Find me in app/views/line_items/create.html.erb</p>

app/views/partials/_footer.html.erb
<footer class="footer-area section_gap">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Top Products</h4>
        <ul>
          <li><a href="#">Managed Website</a></li>
          <li><a href="#">Manage Reputation</a></li>
          <li><a href="#">Power Tools</a></li>
          <li><a href="#">Marketing Service</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Quick Links</h4>
        <ul>
          <li><a href="#">Jobs</a></li>
          <li><a href="#">Brand Assets</a></li>
          <li><a href="#">Investor Relations</a></li>
          <li><a href="#">Terms of Service</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Features</h4>
        <ul>
          <li><a href="#">Jobs</a></li>
          <li><a href="#">Brand Assets</a></li>
          <li><a href="#">Investor Relations</a></li>
          <li><a href="#">Terms of Service</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Resources</h4>
        <ul>
          <li><a href="#">Guides</a></li>
          <li><a href="#">Research</a></li>
          <li><a href="#">Experts</a></li>
          <li><a href="#">Agencies</a></li>
        </ul>
      </div>
      <div class="col-lg-4 col-md-6 single-footer-widget">
        <h4>Newsletter</h4>
        <p>You can trust us. we only send promo offers,</p>
        <div class="form-wrap" id="mc_embed_signup">
          <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                method="get" class="form-inline">
            <input class="form-control" name="EMAIL" placeholder="Your Email Address" onfocus="this.placeholder = ''"
                   onblur="this.placeholder = 'Your Email Address '" required="" type="email">
            <button class="click-btn btn btn-default">Subscribe</button>
            <div style="position: absolute; left: -5000px;">
              <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
            </div>

            <div class="info"></div>
          </form>
        </div>
      </div>
    </div>
    <div class="footer-bottom row align-items-center">
      <p class="footer-text m-0 col-lg-8 col-md-12"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;2019 All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      <div class="col-lg-4 col-md-12 footer-social">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-dribbble"></i></a>
        <a href="#"><i class="fa fa-behance"></i></a>
      </div>
    </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<header class="header_area">
  <div class="top_menu">
    <div class="container">
      <div class="row">
        <div class="col-lg-7">
          <div class="float-left">
            <p>Phone: +01 256 25 235</p>
            <p>email: info@eiser.com</p>
          </div>
        </div>
        <div class="col-lg-5">
          <div class="float-right">
            <ul class="right_side">
              <li>
                <a href="contact.html">
                  Contact Us
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main_menu">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light w-100">
        <!-- Brand and toggle get grouped for better mobile display -->
        <a class="navbar-brand logo_h" href="/">
          <img src="/img/logo.png" alt="" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse offset w-100" id="navbarSupportedContent">
          <div class="row w-100 mr-0">
            <div class="col-lg-7 pr-0">
              <ul class="nav navbar-nav center_nav pull-right">
                <li class="nav-item active">
                  <a class="nav-link" href="/">Home</a>
                </li>
<!--                <li class="nav-item submenu dropdown">-->
<!--                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"-->
<!--                     aria-expanded="false">Shop</a>-->
<!--                  <ul class="dropdown-menu">-->
<!--                    <li class="nav-item">-->
<!--                      <a class="nav-link" href="category.html">Shop Category</a>-->
<!--                    </li>-->
<!--                    <li class="nav-item">-->
<!--                      <a class="nav-link" href="single-product.html">Product Details</a>-->
<!--                    </li>-->
<!--                    <li class="nav-item">-->
<!--                      <a class="nav-link" href="checkout.html">Product Checkout</a>-->
<!--                    </li>-->
<!--                    <li class="nav-item">-->
<!--                      <a class="nav-link" href="cart.html">Shopping Cart</a>-->
<!--                    </li>-->
<!--                  </ul>-->
<!--                </li>-->
                <li class="nav-item">
                  <a class="nav-link" href="#">Contact</a>
                </li>
              </ul>
            </div>

            <div class="col-lg-5 pr-0">
              <ul class="nav navbar-nav navbar-right right_nav pull-right">
                <li class="nav-item">
                  <a href="#" class="icons">
                    <i class="ti-search" aria-hidden="true"></i>
                  </a>
                </li>

                <li class="nav-item">
                  <%= link_to(carts_path, class: "icons") do %>
                    <i class="ti-shopping-cart"></i>
                    <% if @current_cart.total_quantity > 0 %>
                      <span class="badge"><%= @current_cart.total_quantity %></span>
                    <% end %>
                  <% end %>
                </li>

                <li class="nav-item">
                  <a href="#" class="icons">
                    <i class="ti-user" aria-hidden="true"></i>
                  </a>
                </li>

                <li class="nav-item">
                  <a href="#" class="icons">
                    <i class="ti-heart" aria-hidden="true"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </div>
</header>

app/views/partials/_include_css.erb
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="/css/bootstrap.css" />
<link rel="stylesheet" href="/vendors/linericon/style.css" />
<link rel="stylesheet" href="/css/font-awesome.min.css" />
<link rel="stylesheet" href="/css/themify-icons.css" />
<link rel="stylesheet" href="/css/flaticon.css" />
<link rel="stylesheet" href="/vendors/owl-carousel/owl.carousel.min.css" />
<link rel="stylesheet" href="/vendors/lightbox/simpleLightbox.css" />
<link rel="stylesheet" href="/vendors/nice-select/css/nice-select.css" />
<link rel="stylesheet" href="/vendors/animate-css/animate.css" />
<link rel="stylesheet" href="/vendors/jquery-ui/jquery-ui.css" />
<!-- main css -->
<link rel="stylesheet" href="/css/style.css" />
<link rel="stylesheet" href="/css/responsive.css" />

app/views/partials/_include_script.erb
<script src="/js/popper.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/stellar.js"></script>
<script src="/vendors/lightbox/simpleLightbox.min.js"></script>
<script src="/vendors/nice-select/js/jquery.nice-select.min.js"></script>
<script src="/vendors/isotope/imagesloaded.pkgd.min.js"></script>
<script src="/vendors/isotope/isotope-min.js"></script>
<script src="/vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="/js/jquery.ajaxchimp.min.js"></script>
<script src="/vendors/counter-up/jquery.waypoints.min.js"></script>
<script src="/vendors/counter-up/jquery.counterup.js"></script>
<script src="/js/mail-script.js"></script>
<script src="/js/theme.js"></script>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <div class="form-group">
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %>
          prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mt-10">
      <%= form.label :name %>
      <%= form.text_field :name, id: :product_name , class: "single-input"%>
    </div>

    <div class="mt-10">
      <%= form.label :description %>
      <%= form.text_area :description, id: :product_description , class: "single-input", :size => "50x10"%>
    </div>

    <div class="mt-10">
      <%= form.label :price %>
      <%= form.text_field :price, id: :product_price, class: "single-input" %>
    </div>

    <div class="mt-10">
      <%= form.label :image %>
      <%= form.text_field :image, id: :product_image, class: "single-input" %>
    </div>

    <div class="mt-10">
      <%= form.submit "Submit", class: "genric-btn info radius" %>
    </div>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-lg-4 col-md-6">
  <div class="single-product">
    <div class="product-img">
      <img class="img-fluid w-100" src="<%= product.image %>" alt="" />
    </div>
    <div class="product-btm">
      <%= link_to(product_path(product), class: "d-block") do %>
        <h4><%= product.name %></h4>
      <% end %>

      <div class="mt-3">
        <span class="mr-4">$<%= product.price %></span>
      </div>
    </div>
  </div>
</div>

app/views/products/_product_item.html.erb
<div class="col-lg-4 col-md-6">
  <div class="single-product">
    <div class="product-img">
      <img class="img-fluid w-100" src="<%= product.image %>" alt="" />
    </div>
    <div class="product-btm">
      <div class="d-block">
        <h4><%= product.name %></h4>
      </div>

      <div class="mt-3">
        <span class="mr-4">$<%= product.price %></span>
      </div>

      <%= link_to("Edit", edit_product_path(product), class: "genric-btn info radius small mt-10") %>
      <%= link_to("Delete", product_path(product),
                  class: "genric-btn danger radius small mt-10",
                  method: :delete,
                  data: {confirm: "Are you sure you want to delete? This action can't be undone."} )
      %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="product_image_area section_gap_bottom_custom">
  <div class="container">
    <h1>Editing Product</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Show', @product %>

  </div>
</div>

app/views/products/index.html.erb
<!--================Home Banner Area =================-->
<section class="home_banner_area mb-40">
  <div class="banner_inner d-flex align-items-center">
    <div class="container">
      <div class="banner_content row">
        <div class="col-lg-12">
          <p class="sub text-uppercase">men Collection</p>
          <h3><span>Show</span> Your <br />Personal <span>Style</span></h3>
          <h4>Fowl saw dry which a above together place.</h4>
          <a class="main_btn mt-40" href="#feature_product">View Collection</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Home Banner Area =================-->

<!-- Start feature Area -->
<section class="feature-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="single-feature">
          <a href="#" class="title">
            <i class="flaticon-money"></i>
            <h3>Money back gurantee</h3>
          </a>
          <p>Shall open divide a one</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="single-feature">
          <a href="#" class="title">
            <i class="flaticon-truck"></i>
            <h3>Free Delivery</h3>
          </a>
          <p>Shall open divide a one</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="single-feature">
          <a href="#" class="title">
            <i class="flaticon-support"></i>
            <h3>Alway support</h3>
          </a>
          <p>Shall open divide a one</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="single-feature">
          <a href="#" class="title">
            <i class="flaticon-blockchain"></i>
            <h3>Secure payment</h3>
          </a>
          <p>Shall open divide a one</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End feature Area -->

<!--================ Feature Product Area =================-->
<section class="feature_product_area section_gap_top section_gap_bottom_custom" id="feature_product">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="main_title">
          <h2><span>Featured product</span></h2>
          <p>Bring called seed first of third give itself now ment</p>
        </div>
      </div>
    </div>

    <div class="row">
      <% @products.each do |product| %>
        <%= render 'product', product: product %>
      <% end %>
    </div>
  </div>
</section>
<!--================ End Feature Product Area =================-->

<!---->

app/views/products/list.html.erb
<section class="feature_product_area section_gap_top section_gap_bottom_custom">
  <div class="container">
    <%= link_to("New Product", new_product_path, class: "genric-btn info radius large mt-10 mb-20") %>
    <div class="row">
      <% @products.each do |product| %>
        <%= render 'product_item', product: product %>
      <% end %>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<div class="product_image_area section_gap_bottom_custom">
  <div class="container">
    <h1>New Product</h1>

    <%= render 'form', product: @product %>

  </div>
</div>

app/views/products/show.html.erb
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div class="container">
      <div
        class="banner_content d-md-flex justify-content-between align-items-center"
      >
        <div class="mb-3 mb-md-0">
          <h2>Product Details</h2>
          <p>Very us move be blessed multiply night</p>
        </div>
        <div class="page_link">
          <a href="/">Home</a>
          <a href="<%= product_path(@product) %>">Product Details</a>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="product_image_area section_gap_bottom_custom">
  <div class="container">
    <div class="row s_product_inner">
      <div class="col-lg-6">
        <div class="s_product_img">
          <div
            id="carouselExampleIndicators"
            class="carousel slide"
            data-ride="carousel"
          >
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img
                  class="d-block w-100"
                  src="<%= @product.image %>"
                  alt="First slide"
                  />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-1">
        <div class="s_product_text">
          <h3><%= @product.name %></h3>
          <h2>$<%= @product.price %></h2>
          <ul class="list">
            <li>
              <a class="active" href="#">
                <span>Category</span> : Household</a
              >
            </li>
            <li>
              <a href="#"> <span>Availibility</span> : In Stock</a>
            </li>
          </ul>
          <p>
            <%= @product.description %>
          </p>
          <%= form_with(model: LineItem.new, local: true) do |form| %>
            <input
              type="text" name="product_id"
              value="<%= @product.id %>"
              style="display: none"
            />
            <div class="product_count">
              <label for="qty">Quantity:</label>
              <input
                type="text" name="quantity"
                id="sst" maxlength="12"
                value="1" title="Quantity:"
                class="input-text qty"
                />
              <button
                onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
                class="increase items-count"
                type="button"
              >
                <i class="lnr lnr-chevron-up"></i>
              </button>
              <button
                onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 1 ) result.value--;return false;"
                class="reduced items-count"
                type="button"
              >
                <i class="lnr lnr-chevron-down"></i>
              </button>
            </div>
            <div class="card_area">
<!--              <a class="main_btn" href="#">Add to Cart</a>-->
              <%= form.submit "Add to Cart", class: "main_btn" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>